### ISSUE TITLE
[enhancement] Provide names and sizes in output

### ISSUE THREAD

**Issue by max-voloshin** [BitOne/php-meminfo#10]
I wish the extension's output contains names of PHP entities (global variables / class fields / object properties) and its sizes.

Related blog post: http://maxvoloshin.com/2015/01/20/the-destination-of-the-allocated-memory/

Thanks!

**Comment by BitOne** [comment]
Hey @max-voloshin,

I forgot to close this issue, but we now have those features since April 2016.

And now a proper PHP 7 support since v1.0.0 ;)
