### ISSUE TITLE
Segfault with PHP 7.4 due to https://github.com/BitOne/php-meminfo/pull/106 fix

### ISSUE THREAD

**Issue by ahocquard** [BitOne/php-meminfo#108]
php-meminfo does not work with PHP 7.4, despite this PR: 

Actually, the fix I did in #106 does not work with PHP 7.4. The issue is probably because the symbol table is got from zend_execute_data directly. For some reasons, the pointer is not correct since PHP 7.4.

Then, it fails later when trying to iterate over this array of symbols.

**Comment by BitOne** [comment]
Fixed, thanks @ahocquard for the fix :)
