### ISSUE TITLE
Add PHP7 compatibility

### ISSUE THREAD

**Issue by syrm** [BitOne/php-meminfo#21]
Please add PHP7 support :-)

**Comment by BitOne** [comment]
Thanks @oxman, working on it ;)

**Comment by oxman** [comment]
Any new ? :-)

**Comment by julienDonnadieu** [comment]
any release date planned?

**Comment by BitOne** [comment]
Very very very late, but done !! Enjoy v1.0.0 with PHP 7 support !

**Comment by jdecool** [comment]
Great news ! Thank you for this extension :)
