### ISSUE TITLE
Method "meminfo_size_info" undefined

### ISSUE THREAD

**Issue by FabienSerny** [BitOne/php-meminfo#23]
Hello,

The method « meminfo_size_info » is in the GitHub documentation but it is considered as undefined when I call it. The others functions work well.
Any idea ?

Fabien

**Comment by BitOne** [comment]
Thank @FabienSerny,

It's indeed a documentation problem. The method name is now `meminfo_info_dump()`

**Comment by BitOne** [comment]
Fixed documentation and method name (now it's `meminfo_dump`, shorter, easier ;) )
