### ISSUE TITLE
Create new tag

### ISSUE THREAD

**Issue by jdecool** [BitOne/php-meminfo#26]
Hello,

First of all, thanks for this tool. 

To simplify installation for Mac users, I create an homebrew (MacOS package manager) formula.

I notice, that there is some differences beetween the last tag (v0.3.0) and the master. Is it possible to create a new tag to allow Mac users to retrieve a recent version of this extension ?

Thanks.

**Comment by BitOne** [comment]
New tag v1.0.0 freshly created ;)
