### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by atis2345** [BitOne/php-meminfo#38]
Hello.
Extension not work for `PHP 7.1.6-1`.

**Comment by cordovapolymer** [comment]
@BitOne bump!

**Comment by sepehr** [comment]
@BitOne Boom!

**Comment by cordovapolymer** [comment]
@BitOne , any hope php7 will be supported ?

**Comment by BitOne** [comment]
Thanks @atis2345 , @sepehr and @cordovapolymer  for your patience people !
The new v1.0.0 version now supports PHP 7.x !

**Comment by cordovapolymer** [comment]
@BitOne wow! Thank you so much!
