### ISSUE TITLE
Brew install fails

### ISSUE THREAD

**Issue by SudoGetBeer** [BitOne/php-meminfo#61]
Hey,

first of all thanks for creating this package.

But my issue is that I can not install it with brew.

```
$ brew install php71-meminfo 
Error: No available formula with the name "php71-meminfo" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

I alos tried 
brew install php72-meminfo
brew install php-meminfo

**Comment by nmdimas** [comment]
PHP was migrated to core in new version Brew and php extension were deleted. Now you can install the extension only through PECL. But meminfo does not exist in PECL.

**Comment by BitOne** [comment]
Thanks @nmdimas , I will update the documentation accordingly.

@SudoGetBeer : you can compile it yourself if needed:
https://github.com/BitOne/php-meminfo#compilation-instructions
